import { describe, expect, it } from "vitest";
import {
  marshalChangeEntry,
  MemDeviceStorage,
  OP_DELETE,
  OP_PUT,
  ReplicationEngine,
  unmarshalChangeEntry,
  type ChangeEntry,
  type DeviceRecord,
} from "../src/devicesync.js";

const enc = new TextEncoder();
const dec = new TextDecoder();

// Golden JSON generated by Go's encoding/json for the same values.
const GOLDEN_PUT =
  '{"seq":7,"timestamp":1751852000123,"table":"notes","record_id":"n-01","op":0,"body":"eyJ0ZXh0IjoiaGkifQ=="}';
const GOLDEN_DELETE =
  '{"seq":8,"timestamp":1751852000999,"table":"notes","record_id":"n-01","op":1,"body":null}';

describe("devicesync wire format (golden vectors from Go)", () => {
  it("marshals ChangeEntry byte-identically to Go", () => {
    expect(
      dec.decode(
        marshalChangeEntry({
          seq: 7,
          timestamp: 1751852000123,
          table: "notes",
          recordId: "n-01",
          op: OP_PUT,
          body: enc.encode('{"text":"hi"}'),
        }),
      ),
    ).toBe(GOLDEN_PUT);
    expect(
      dec.decode(
        marshalChangeEntry({
          seq: 8,
          timestamp: 1751852000999,
          table: "notes",
          recordId: "n-01",
          op: OP_DELETE,
          body: null,
        }),
      ),
    ).toBe(GOLDEN_DELETE);
  });

  it("unmarshals Go-produced ChangeEntry JSON", () => {
    const put = unmarshalChangeEntry(enc.encode(GOLDEN_PUT));
    expect(put.seq).toBe(7);
    expect(put.recordId).toBe("n-01");
    expect(put.op).toBe(OP_PUT);
    expect(dec.decode(put.body!)).toBe('{"text":"hi"}');
    const del = unmarshalChangeEntry(enc.encode(GOLDEN_DELETE));
    expect(del.op).toBe(OP_DELETE);
    expect(del.body).toBeNull();
  });
});

function makeEngine(opts: { retention?: Parameters<typeof mk>[0] } = {}) {
  return mk(opts.retention ?? null);
}

function mk(retention: { timeBased: boolean; maxAgeMs?: number; maxCount?: number } | null) {
  const storage = new MemDeviceStorage();
  const sent: Array<{ peerId: string; payload: Uint8Array }> = [];
  let now = 1_000_000;
  const engine = new ReplicationEngine({
    storage,
    send: async (peerId, payload) => {
      sent.push({ peerId, payload });
    },
    peers: async () => ["dev-2", "dev-3"],
    selfDID: "did:self",
    retention,
    now: () => now,
  });
  return { engine, storage, sent, setNow: (t: number) => (now = t) };
}

describe("ReplicationEngine (mirroring replication_test.go)", () => {
  it("put stores locally, logs the change, and broadcasts to all peers", async () => {
    const { engine, storage, sent } = makeEngine();
    await engine.put("notes", "n1", enc.encode("hello"));

    const rec = await storage.get("notes", "n1");
    expect(dec.decode(rec!.body!)).toBe("hello");
    expect(await storage.latestSeq()).toBe(1);

    expect(sent.map((s) => s.peerId)).toEqual(["dev-2", "dev-3"]);
    const entry = unmarshalChangeEntry(sent[0]!.payload);
    expect(entry.table).toBe("notes");
    expect(entry.recordId).toBe("n1");
    expect(entry.op).toBe(OP_PUT);
  });

  it("delete removes locally and broadcasts a delete entry", async () => {
    const { engine, storage, sent } = makeEngine();
    await engine.put("notes", "n1", enc.encode("hello"));
    await engine.delete("notes", "n1");
    expect(await storage.get("notes", "n1")).toBeNull();
    const entry = unmarshalChangeEntry(sent.at(-1)!.payload);
    expect(entry.op).toBe(OP_DELETE);
  });

  it("broadcast failures are ignored (store-and-forward covers offline peers)", async () => {
    const storage = new MemDeviceStorage();
    const engine = new ReplicationEngine({
      storage,
      send: async () => {
        throw new Error("offline");
      },
      peers: async () => ["dev-2"],
      selfDID: "did:self",
    });
    await engine.put("notes", "n1", enc.encode("x")); // no throw
    expect(await storage.get("notes", "n1")).not.toBeNull();
  });

  it("handleIncoming applies with last-write-wins", async () => {
    const { engine, storage } = makeEngine();
    const base: ChangeEntry = {
      seq: 1,
      timestamp: 100,
      table: "notes",
      recordId: "n1",
      op: OP_PUT,
      body: enc.encode("v1"),
    };
    await engine.handleIncoming(base);
    expect(dec.decode((await storage.get("notes", "n1"))!.body!)).toBe("v1");

    await engine.handleIncoming({ ...base, seq: 2, timestamp: 200, body: enc.encode("v2") });
    expect(dec.decode((await storage.get("notes", "n1"))!.body!)).toBe("v2");

    await engine.handleIncoming({ ...base, seq: 3, timestamp: 150, body: enc.encode("old") });
    expect(dec.decode((await storage.get("notes", "n1"))!.body!)).toBe("v2");

    await engine.handleIncoming({ ...base, seq: 4, timestamp: 300, op: OP_DELETE, body: null });
    expect(await storage.get("notes", "n1")).toBeNull();
  });

  it("syncWith sends nothing when the peer is up to date", async () => {
    const { engine } = makeEngine();
    let entries: ChangeEntry[] | undefined;
    await engine.syncWith({
      latestSeq: async () => 100,
      sendEntries: async (e) => {
        entries = e;
      },
    });
    expect(entries).toEqual([]);
  });

  it("syncWith sends incremental changes since the peer's seq", async () => {
    const { engine } = makeEngine();
    await engine.put("notes", "n1", enc.encode("a"));
    await engine.put("notes", "n2", enc.encode("b"));
    await engine.put("notes", "n3", enc.encode("c"));

    let entries: ChangeEntry[] = [];
    await engine.syncWith({
      latestSeq: async () => 1,
      sendEntries: async (e) => {
        entries = e;
      },
    });
    expect(entries.map((e) => e.recordId)).toEqual(["n2", "n3"]);
  });

  it("syncWith falls back to a full dump when a gap is detected", async () => {
    const { engine, storage, setNow } = makeEngine();
    await engine.put("notes", "n1", enc.encode("a"));
    await engine.put("notes", "n2", enc.encode("b"));
    setNow(2_000_000);
    await storage.truncateChangeLog(2); // simulate pruned log: minSeq becomes 2

    let dump: DeviceRecord[] = [];
    await engine.syncWith({
      latestSeq: async () => 1,
      sendEntries: async () => {
        throw new Error("should not send incremental");
      },
      sendFullDump: async (records) => {
        dump = records;
      },
    });
    expect(dump.map((r) => r.id).sort()).toEqual(["n1", "n2"]);
  });

  it("syncWith throws on a gap when no full dump handler exists", async () => {
    const { engine, storage } = makeEngine();
    await engine.put("notes", "n1", enc.encode("a"));
    await engine.put("notes", "n2", enc.encode("b"));
    await storage.truncateChangeLog(2);
    await expect(
      engine.syncWith({
        latestSeq: async () => 1,
        sendEntries: async () => {},
      }),
    ).rejects.toThrow("changelog gap");
  });

  it("time-based retention prunes entries older than maxAge", async () => {
    const { engine, storage, setNow } = mk({ timeBased: true, maxAgeMs: 1_000 });
    setNow(10_000);
    await engine.put("notes", "n1", enc.encode("a"));
    setNow(20_000); // n1's entry (t=10000) is now older than 20000-1000
    await engine.put("notes", "n2", enc.encode("b"));
    const entries = await storage.changesSince(0);
    expect(entries.map((e) => e.recordId)).toEqual(["n2"]);
  });

  it("count-based retention keeps at most maxCount entries", async () => {
    const { engine, storage } = mk({ timeBased: false, maxCount: 2 });
    await engine.put("notes", "n1", enc.encode("a"));
    await engine.put("notes", "n2", enc.encode("b"));
    await engine.put("notes", "n3", enc.encode("c"));
    const entries = await storage.changesSince(0);
    expect(entries.length).toBeLessThanOrEqual(2);
    expect(entries.at(-1)!.recordId).toBe("n3");
  });
});
