import { describe, expect, it } from "vitest";
import {
  GroupShareError,
  GroupShareLayer,
  marshalSharedRecord,
  marshalSubAnnouncement,
  MemSharedStorage,
  MemSubscriptionStore,
  topicMatches,
  unmarshalSharedRecord,
  unmarshalSubAnnouncement,
  type Channel,
  type SharedRecord,
} from "../src/groupshare.js";
import { RoleDAG } from "../src/role.js";

const enc = new TextEncoder();
const dec = new TextDecoder();

// Golden JSON generated by Go's encoding/json for the same values.
const GOLDEN_RECORD =
  '{"id":"sr-01","channel":"visits","topic":"area/NRT-001-05","group_id":"grp-01","did":"did:key:zTest","timestamp":1751852000123,"body":"eyJzdGF0dXMiOiJtZXQifQ==","deleted":false}';
const GOLDEN_NO_TOPIC =
  '{"id":"sr-02","channel":"visits","group_id":"grp-01","did":"did:a","timestamp":42,"body":"eA==","deleted":false}';
const GOLDEN_DELETED =
  '{"id":"sr-01","channel":"visits","group_id":"grp-01","did":"did:a","timestamp":99,"body":null,"deleted":true}';
const GOLDEN_ANNOUNCEMENT =
  '{"did":"did:key:zTest","channel":"visits","topics":["area/NRT-001-05","area/NRT-001-06"]}';
const GOLDEN_ANNOUNCEMENT_EMPTY =
  '{"did":"did:a","channel":"visits","topics":[]}';

describe("groupshare wire format (golden vectors from Go)", () => {
  it("marshals SharedRecord byte-identically to Go (topic omitted when empty)", () => {
    expect(
      dec.decode(
        marshalSharedRecord({
          id: "sr-01",
          channel: "visits",
          topic: "area/NRT-001-05",
          groupId: "grp-01",
          did: "did:key:zTest",
          timestamp: 1751852000123,
          body: enc.encode('{"status":"met"}'),
          deleted: false,
        }),
      ),
    ).toBe(GOLDEN_RECORD);
    expect(
      dec.decode(
        marshalSharedRecord({
          id: "sr-02",
          channel: "visits",
          topic: "",
          groupId: "grp-01",
          did: "did:a",
          timestamp: 42,
          body: enc.encode("x"),
          deleted: false,
        }),
      ),
    ).toBe(GOLDEN_NO_TOPIC);
    expect(
      dec.decode(
        marshalSharedRecord({
          id: "sr-01",
          channel: "visits",
          topic: "",
          groupId: "grp-01",
          did: "did:a",
          timestamp: 99,
          body: null,
          deleted: true,
        }),
      ),
    ).toBe(GOLDEN_DELETED);
  });

  it("unmarshals Go-produced SharedRecord JSON", () => {
    const r = unmarshalSharedRecord(enc.encode(GOLDEN_RECORD));
    expect(r.topic).toBe("area/NRT-001-05");
    expect(r.groupId).toBe("grp-01");
    expect(dec.decode(r.body!)).toBe('{"status":"met"}');
    const noTopic = unmarshalSharedRecord(enc.encode(GOLDEN_NO_TOPIC));
    expect(noTopic.topic).toBe("");
    const del = unmarshalSharedRecord(enc.encode(GOLDEN_DELETED));
    expect(del.deleted).toBe(true);
    expect(del.body).toBeNull();
  });

  it("marshals/unmarshals SubAnnouncement byte-identically to Go", () => {
    expect(
      dec.decode(
        marshalSubAnnouncement({
          did: "did:key:zTest",
          channel: "visits",
          topics: ["area/NRT-001-05", "area/NRT-001-06"],
        }),
      ),
    ).toBe(GOLDEN_ANNOUNCEMENT);
    expect(
      dec.decode(
        marshalSubAnnouncement({ did: "did:a", channel: "visits", topics: [] }),
      ),
    ).toBe(GOLDEN_ANNOUNCEMENT_EMPTY);
    const ann = unmarshalSubAnnouncement(enc.encode(GOLDEN_ANNOUNCEMENT));
    expect(ann.topics).toEqual(["area/NRT-001-05", "area/NRT-001-06"]);
  });
});

describe("topicMatches", () => {
  it("matches exact topics and the wildcard", () => {
    expect(topicMatches(["a", "b"], "a")).toBe(true);
    expect(topicMatches(["*"], "anything")).toBe(true);
    expect(topicMatches(["a"], "b")).toBe(false);
    expect(topicMatches([], "a")).toBe(false);
  });
});

/* ------------------------------------------------------------------ */

interface Harness {
  layer: GroupShareLayer;
  storage: MemSharedStorage;
  sent: Array<{ members: string[]; payload: Uint8Array }>;
  announced: Array<{ members: string[]; payload: Uint8Array }>;
  remoteSubs: MemSubscriptionStore;
  localSubs: MemSubscriptionStore;
  setNow(t: number): void;
}

function makeHarness(
  channel: Partial<Channel> = {},
  members: string[] = ["did:m1", "did:m2"],
): Harness {
  const storage = new MemSharedStorage();
  const sent: Harness["sent"] = [];
  const announced: Harness["announced"] = [];
  const remoteSubs = new MemSubscriptionStore();
  const localSubs = new MemSubscriptionStore();
  let now = 1_000_000;
  const layer = new GroupShareLayer({
    storage,
    memberResolver: { memberDIDsForGroup: async () => members },
    sendGroup: async (m, p) => {
      sent.push({ members: m, payload: p });
    },
    selfDID: "did:self",
    localSubs,
    remoteSubs,
    sendSubAnnounce: async (m, p) => {
      announced.push({ members: m, payload: p });
    },
    now: () => now,
  });
  layer.registerChannel({
    name: "visits",
    groupId: "grp-01",
    ...channel,
  });
  return {
    layer,
    storage,
    sent,
    announced,
    remoteSubs,
    localSubs,
    setNow: (t) => (now = t),
  };
}

describe("GroupShareLayer (mirroring groupshare_test.go)", () => {
  it("rejects duplicate channel registration", () => {
    const { layer } = makeHarness();
    expect(() =>
      layer.registerChannel({ name: "visits", groupId: "g" }),
    ).toThrow(GroupShareError);
  });

  it("put stores the record and broadcasts to members", async () => {
    const { layer, storage, sent } = makeHarness();
    await layer.put("visits", "t1", "id1", enc.encode("hello"));

    const stored = await storage.getShared("visits", "id1");
    expect(stored).not.toBeNull();
    expect(stored!.did).toBe("did:self");
    expect(stored!.groupId).toBe("grp-01");

    expect(sent).toHaveLength(1);
    expect(sent[0]!.members).toEqual(["did:m1", "did:m2"]);
    const rec = unmarshalSharedRecord(sent[0]!.payload);
    expect(rec.id).toBe("id1");
    expect(rec.topic).toBe("t1");
  });

  it("put to an unknown channel fails", async () => {
    const { layer } = makeHarness();
    await expect(layer.put("nope", "", "id", enc.encode("x"))).rejects.toThrow(
      GroupShareError,
    );
  });

  it("put is denied by the access policy", async () => {
    const { layer } = makeHarness({
      access: { canWrite: () => false, canRead: () => true },
    });
    await expect(
      layer.put("visits", "", "id", enc.encode("x")),
    ).rejects.toMatchObject({
      code: "access_denied",
    });
  });

  it("delete removes locally and broadcasts a tombstone", async () => {
    const { layer, storage, sent } = makeHarness();
    await layer.put("visits", "", "id1", enc.encode("v"));
    await layer.delete("visits", "", "id1");
    expect(await storage.getShared("visits", "id1")).toBeNull();
    const tomb = unmarshalSharedRecord(sent[1]!.payload);
    expect(tomb.deleted).toBe(true);
    expect(tomb.body).toBeNull();
  });

  it("handleIncoming applies with last-write-wins and handles tombstones", async () => {
    const { layer, storage } = makeHarness();
    const base: SharedRecord = {
      id: "id1",
      channel: "visits",
      topic: "",
      groupId: "grp-01",
      did: "did:m1",
      timestamp: 100,
      body: enc.encode("v1"),
      deleted: false,
    };
    await layer.handleIncoming(marshalSharedRecord(base));
    expect(dec.decode((await storage.getShared("visits", "id1"))!.body!)).toBe(
      "v1",
    );

    await layer.handleIncoming(
      marshalSharedRecord({ ...base, timestamp: 200, body: enc.encode("v2") }),
    );
    expect(dec.decode((await storage.getShared("visits", "id1"))!.body!)).toBe(
      "v2",
    );

    await layer.handleIncoming(
      marshalSharedRecord({ ...base, timestamp: 150, body: enc.encode("old") }),
    );
    expect(dec.decode((await storage.getShared("visits", "id1"))!.body!)).toBe(
      "v2",
    );

    await layer.handleIncoming(
      marshalSharedRecord({
        ...base,
        timestamp: 300,
        body: null,
        deleted: true,
      }),
    );
    expect(await storage.getShared("visits", "id1")).toBeNull();
  });

  it("handleIncoming silently drops unknown channels", async () => {
    const { layer } = makeHarness();
    await layer.handleIncoming(
      marshalSharedRecord({
        id: "x",
        channel: "unknown",
        topic: "",
        groupId: "g",
        did: "did:a",
        timestamp: 1,
        body: enc.encode("x"),
        deleted: false,
      }),
    );
  });

  it("handleIncoming enforces the access policy (read side)", async () => {
    const { layer } = makeHarness({
      access: { canWrite: () => true, canRead: (did) => did !== "did:banned" },
    });
    const rec: SharedRecord = {
      id: "x",
      channel: "visits",
      topic: "",
      groupId: "grp-01",
      did: "did:banned",
      timestamp: 1,
      body: enc.encode("x"),
      deleted: false,
    };
    await expect(
      layer.handleIncoming(marshalSharedRecord(rec)),
    ).rejects.toMatchObject({
      code: "access_denied",
    });
  });

  it("handleIncoming validates the schema for non-deletes", async () => {
    const { layer } = makeHarness({
      schema: {
        validate: (body) => {
          JSON.parse(dec.decode(body ?? new Uint8Array()));
        },
      },
    });
    const rec: SharedRecord = {
      id: "x",
      channel: "visits",
      topic: "",
      groupId: "grp-01",
      did: "did:m1",
      timestamp: 1,
      body: enc.encode("not json"),
      deleted: false,
    };
    await expect(
      layer.handleIncoming(marshalSharedRecord(rec)),
    ).rejects.toMatchObject({
      code: "schema_validation",
    });
    // Tombstones skip schema validation.
    await layer.handleIncoming(
      marshalSharedRecord({ ...rec, timestamp: 2, body: null, deleted: true }),
    );
  });

  it("retention: expired records are hidden, dropped on arrival, and purged", async () => {
    const { layer, storage, setNow } = makeHarness({ retentionMs: 1_000 });
    setNow(10_000);
    await layer.put("visits", "", "id1", enc.encode("v"));
    expect(await layer.get("visits", "id1")).not.toBeNull();

    setNow(11_000); // exactly at expiry
    expect(await layer.get("visits", "id1")).toBeNull();
    expect(await layer.list("visits")).toHaveLength(0);
    expect(await layer.dump("grp-01")).toHaveLength(0);

    // Incoming expired record is silently dropped.
    await layer.handleIncoming(
      marshalSharedRecord({
        id: "id2",
        channel: "visits",
        topic: "",
        groupId: "grp-01",
        did: "did:m1",
        timestamp: 9_000,
        body: enc.encode("old"),
        deleted: false,
      }),
    );
    expect(await storage.getShared("visits", "id2")).toBeNull();

    // Purge physically removes expired rows (deleteExpired uses
    // timestamp < now - retention, so move past the exact boundary).
    setNow(12_000);
    expect(await layer.purge("visits")).toBe(1);
    expect(await storage.getShared("visits", "id1")).toBeNull();
  });

  it("purge returns 0 for permanent channels", async () => {
    const { layer } = makeHarness(); // no retention
    await layer.put("visits", "", "id1", enc.encode("v"));
    expect(await layer.purge("visits")).toBe(0);
  });

  it("restore applies with last-write-wins and reports the applied count", async () => {
    const { layer, storage } = makeHarness();
    await layer.put("visits", "", "id1", enc.encode("mine"));
    const existing = await storage.getShared("visits", "id1");
    const applied = await layer.restore([
      {
        ...existing!,
        timestamp: existing!.timestamp - 1,
        body: enc.encode("older"),
      },
      {
        id: "id9",
        channel: "visits",
        topic: "",
        groupId: "grp-01",
        did: "did:m1",
        timestamp: 5,
        body: enc.encode("new"),
        deleted: false,
      },
    ]);
    expect(applied).toBe(1);
    expect(dec.decode((await storage.getShared("visits", "id1"))!.body!)).toBe(
      "mine",
    );
    expect(await storage.getShared("visits", "id9")).not.toBeNull();
  });

  it("role permissions: write denied locally, read denied on arrival", async () => {
    const dag = RoleDAG.build({ editor: { includes: [] } });
    const roles = new Map<string, string>([
      ["did:self", ""],
      ["did:m1", "editor"],
    ]);
    const storage = new MemSharedStorage();
    const layer = new GroupShareLayer({
      storage,
      memberResolver: { memberDIDsForGroup: async () => ["did:m1"] },
      sendGroup: async () => {},
      selfDID: "did:self",
      roleDAG: dag,
      memberRoleResolver: {
        memberRole: async (_g, did) => roles.get(did) ?? "",
      },
    });
    layer.registerChannel({
      name: "visits",
      groupId: "grp-01",
      perms: { read: "editor", write: "editor", delete: "editor" },
    });

    // Self has no role → write denied.
    await expect(
      layer.put("visits", "", "id", enc.encode("x")),
    ).rejects.toMatchObject({
      code: "access_denied",
    });

    // Incoming from a non-editor DID → read denied.
    const rec: SharedRecord = {
      id: "x",
      channel: "visits",
      topic: "",
      groupId: "grp-01",
      did: "did:stranger",
      timestamp: 1,
      body: enc.encode("x"),
      deleted: false,
    };
    await expect(
      layer.handleIncoming(marshalSharedRecord(rec)),
    ).rejects.toMatchObject({
      code: "access_denied",
    });

    // Incoming from an editor is accepted.
    await layer.handleIncoming(marshalSharedRecord({ ...rec, did: "did:m1" }));
    expect(await storage.getShared("visits", "x")).not.toBeNull();
  });
});

describe("subscription filtering (mirroring subscription_test.go)", () => {
  it("subscribe stores locally and broadcasts an announcement", async () => {
    const { layer, localSubs, announced } = makeHarness();
    await layer.subscribe("visits", ["area/1", "area/2"]);
    expect(await localSubs.getSubscription("did:self", "visits")).toEqual([
      "area/1",
      "area/2",
    ]);
    expect(announced).toHaveLength(1);
    const ann = unmarshalSubAnnouncement(announced[0]!.payload);
    expect(ann.did).toBe("did:self");
    expect(ann.topics).toEqual(["area/1", "area/2"]);
  });

  it("handleSubAnnouncement stores the peer's subscription and rejects spoofing", async () => {
    const { layer, remoteSubs } = makeHarness();
    const payload = marshalSubAnnouncement({
      did: "did:m1",
      channel: "visits",
      topics: ["area/1"],
    });
    await layer.handleSubAnnouncement("did:m1", payload);
    expect(await remoteSubs.getSubscription("did:m1", "visits")).toEqual([
      "area/1",
    ]);

    await expect(
      layer.handleSubAnnouncement("did:imposter", payload),
    ).rejects.toMatchObject({
      code: "sub_announcement_did_mismatch",
    });
  });

  it("broadcast filters members by their subscriptions", async () => {
    const { layer, remoteSubs, sent } = makeHarness({}, [
      "did:m1",
      "did:m2",
      "did:m3",
    ]);
    // m1 subscribes to area/1 only, m2 to everything, m3 unknown (no announcement).
    await remoteSubs.setSubscription("did:m1", "visits", ["area/1"]);
    await remoteSubs.setSubscription("did:m2", "visits", ["*"]);

    await layer.put("visits", "area/1", "a", enc.encode("x"));
    expect(sent[0]!.members).toEqual(["did:m1", "did:m2", "did:m3"]);

    await layer.put("visits", "area/9", "b", enc.encode("y"));
    expect(sent[1]!.members).toEqual(["did:m2", "did:m3"]); // m1 filtered out

    // Unsubscribed ([]) member receives nothing.
    await remoteSubs.setSubscription("did:m2", "visits", []);
    await remoteSubs.setSubscription("did:m3", "visits", []);
    await remoteSubs.setSubscription("did:m1", "visits", []);
    await layer.put("visits", "area/1", "c", enc.encode("z"));
    expect(sent).toHaveLength(2); // no send when all filtered
  });

  it("announceAllSubscriptions re-broadcasts every local subscription", async () => {
    const { layer, announced } = makeHarness();
    await layer.subscribe("visits", ["area/1"]);
    announced.length = 0;
    await layer.announceAllSubscriptions();
    expect(announced).toHaveLength(1);
    expect(unmarshalSubAnnouncement(announced[0]!.payload).topics).toEqual([
      "area/1",
    ]);
  });
});
