import { generateKeyPairFromSeed } from "@libp2p/crypto/keys";
import { describe, expect, it } from "vitest";
import { generateIdentity, identityFromPrivateKey } from "../src/did.js";
import {
  createToken,
  exportPrivateKey,
  importIdentity,
  PairingError,
  PairingSession,
  validateToken,
} from "../src/pairing.js";
import { bytesToHex, GOLDEN, hexToBytes } from "./vectors.js";

// Generated by Go: did.UserIdentity.ExportPrivKey() (crypto.MarshalPrivateKey)
// for the GOLDEN seed key. Cross-implementation pairing depends on this.
const GOLDEN_EXPORTED_KEY_HEX =
  "080112400102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f2079b5562e8fe654f94078b112e8a98ba7901f853ae695bed7e0e3910bad049664";

describe("key export/import (golden vector from Go)", () => {
  it("exports the private key byte-identically to Go's MarshalPrivateKey", async () => {
    const priv = await generateKeyPairFromSeed("Ed25519", hexToBytes(GOLDEN.seedHex));
    const id = identityFromPrivateKey(priv);
    expect(bytesToHex(exportPrivateKey(id))).toBe(GOLDEN_EXPORTED_KEY_HEX);
  });

  it("imports a Go-exported key and derives the same DID", () => {
    const id = importIdentity(hexToBytes(GOLDEN_EXPORTED_KEY_HEX));
    expect(id.did).toBe(GOLDEN.did);
  });
});

describe("pairing token (mirroring token_test.go)", () => {
  it("validates a matching, unexpired secret", () => {
    let now = 1_000_000;
    const token = createToken(60_000, () => now);
    expect(token.secret).toMatch(/^[0-9a-f]{32}$/);
    validateToken(token.secret, token, () => now); // no throw
  });

  it("rejects a wrong secret", () => {
    const token = createToken(60_000);
    expect(() => validateToken("wrong", token)).toThrow(PairingError);
    try {
      validateToken("wrong", token);
    } catch (err) {
      expect((err as PairingError).code).toBe("token_invalid");
    }
  });

  it("rejects an expired token", () => {
    let now = 1_000_000;
    const token = createToken(60_000, () => now);
    now += 60_001;
    try {
      validateToken(token.secret, token, () => now);
      throw new Error("should have thrown");
    } catch (err) {
      expect((err as PairingError).code).toBe("token_expired");
    }
  });
});

describe("PairingSession (mirroring protocol_test.go)", () => {
  it("transfers the user key to a device presenting the correct secret", async () => {
    const existing = await generateIdentity();
    const session = new PairingSession(existing, 60_000);
    const key = session.complete(session.token.secret);
    const restored = importIdentity(key);
    expect(restored.did).toBe(existing.did);
  });

  it("rejects a wrong secret and an expired session", async () => {
    const existing = await generateIdentity();
    let now = 1_000_000;
    const session = new PairingSession(existing, 60_000, () => now);
    expect(() => session.complete("nope")).toThrow(PairingError);
    now += 120_000;
    expect(() => session.complete(session.token.secret)).toThrow(PairingError);
  });
});
