import { describe, expect, it } from "vitest";
import {
  marshalRecord,
  MemStorage,
  SyncLayer,
  unmarshalRecord,
  type SyncRecord,
} from "../src/syncdb.js";

const enc = new TextEncoder();
const dec = new TextDecoder();

// Golden JSON generated by Go's encoding/json for the same records.
const GOLDEN_RECORD_JSON =
  '{"id":"rec-0001","groupId":"grp-01","did":"did:key:z2DYcAYcYraFMjjqMjjR4rdxDRknbRpHoYRCWpKVhg9heA7","timestamp":1751852000123,"body":"eyJuYW1lIjoidmlzaXQifQ==","deleted":false}';
const GOLDEN_DELETED_JSON =
  '{"id":"rec-0001","groupId":"grp-01","did":"did:a","timestamp":1751852000999,"body":null,"deleted":true}';

describe("SyncRecord wire format (golden vectors from Go)", () => {
  it("marshals byte-identically to Go", () => {
    const record: SyncRecord = {
      id: "rec-0001",
      groupId: "grp-01",
      did: "did:key:z2DYcAYcYraFMjjqMjjR4rdxDRknbRpHoYRCWpKVhg9heA7",
      timestamp: 1751852000123,
      body: enc.encode('{"name":"visit"}'),
      deleted: false,
    };
    expect(dec.decode(marshalRecord(record))).toBe(GOLDEN_RECORD_JSON);
  });

  it("marshals a deleted record with null body byte-identically to Go", () => {
    const record: SyncRecord = {
      id: "rec-0001",
      groupId: "grp-01",
      did: "did:a",
      timestamp: 1751852000999,
      body: null,
      deleted: true,
    };
    expect(dec.decode(marshalRecord(record))).toBe(GOLDEN_DELETED_JSON);
  });

  it("unmarshals Go-produced JSON", () => {
    const r = unmarshalRecord(enc.encode(GOLDEN_RECORD_JSON));
    expect(r.id).toBe("rec-0001");
    expect(r.groupId).toBe("grp-01");
    expect(r.timestamp).toBe(1751852000123);
    expect(dec.decode(r.body!)).toBe('{"name":"visit"}');
    expect(r.deleted).toBe(false);

    const d = unmarshalRecord(enc.encode(GOLDEN_DELETED_JSON));
    expect(d.deleted).toBe(true);
    expect(d.body).toBeNull();
  });
});

describe("SyncLayer (mirroring sync_test.go)", () => {
  function makeLayer(members: string[] = []) {
    const storage = new MemStorage();
    const sent: Array<{ memberDIDs: string[]; payload: Uint8Array }> = [];
    const layer = new SyncLayer(
      storage,
      { memberDIDsForGroup: async () => members },
      async (memberDIDs, payload) => {
        sent.push({ memberDIDs, payload });
      },
      "did:self",
    );
    return { storage, sent, layer };
  }

  it("put attaches meta, stores, and delivers to group members", async () => {
    const { storage, sent, layer } = makeLayer(["did:a", "did:b"]);
    const record = await layer.put("g1", enc.encode("hello"));

    expect(record.id).not.toBe("");
    expect(record.groupId).toBe("g1");
    expect(record.did).toBe("did:self");
    expect(record.timestamp).toBeGreaterThan(0);
    expect(dec.decode(record.body!)).toBe("hello");

    const got = await storage.get(record.id);
    expect(got).not.toBeNull();
    expect(dec.decode(got!.body!)).toBe("hello");

    expect(sent).toHaveLength(1);
    expect(sent[0]!.memberDIDs).toEqual(["did:a", "did:b"]);
    const decoded = unmarshalRecord(sent[0]!.payload);
    expect(decoded.id).toBe(record.id);
    expect(dec.decode(decoded.body!)).toBe("hello");
  });

  it("handleIncoming applies newer records (last-write-wins)", async () => {
    const { storage, layer } = makeLayer();
    await layer.handleIncoming(
      marshalRecord({ id: "id1", groupId: "g1", did: "did:a", timestamp: 100, body: enc.encode("v1"), deleted: false }),
    );
    expect(dec.decode((await storage.get("id1"))!.body!)).toBe("v1");

    await layer.handleIncoming(
      marshalRecord({ id: "id1", groupId: "g1", did: "did:b", timestamp: 200, body: enc.encode("v2"), deleted: false }),
    );
    expect(dec.decode((await storage.get("id1"))!.body!)).toBe("v2");
  });

  it("handleIncoming skips older or equal records", async () => {
    const { storage, layer } = makeLayer();
    await layer.handleIncoming(
      marshalRecord({ id: "id1", groupId: "g1", did: "did:a", timestamp: 200, body: enc.encode("v2"), deleted: false }),
    );
    await layer.handleIncoming(
      marshalRecord({ id: "id1", groupId: "g1", did: "did:b", timestamp: 100, body: enc.encode("v1"), deleted: false }),
    );
    expect(dec.decode((await storage.get("id1"))!.body!)).toBe("v2");

    await layer.handleIncoming(
      marshalRecord({ id: "id1", groupId: "g1", did: "did:c", timestamp: 200, body: enc.encode("equal"), deleted: false }),
    );
    expect(dec.decode((await storage.get("id1"))!.body!)).toBe("v2");
  });

  it("handleIncoming applies deletions", async () => {
    const { storage, layer } = makeLayer();
    await layer.handleIncoming(
      marshalRecord({ id: "id1", groupId: "g1", did: "did:a", timestamp: 100, body: enc.encode("v1"), deleted: false }),
    );
    await layer.handleIncoming(
      marshalRecord({ id: "id1", groupId: "g1", did: "did:a", timestamp: 200, body: null, deleted: true }),
    );
    expect(await storage.get("id1")).toBeNull();
  });
});
